services:
  flat-apply:
    image: ghcr.io/eisimo/flat-apply:latest
    container_name: flat-apply
    env_file:
      - .env
    environment:
      - HEADLESS=True
      - FULL_AUTO_MODE=True
      - SUBMIT_FORMS=False
    restart: unless-stopped
