[application_success]
en = "Successfully applied."
de = "Erfolgreich beworben."

[application_failed]
en = "Unsuccessful application."
de = "Nicht erfolgreich beworben."

[application_success_dry]
en = "Dryrun. No form submitted."
de = "Trockenlauf. Formular nicht abgeschickt."

[submit_conformation_msg_not_found]
en = "Submission conformation message not found."
de = "Best채tigungsnachricht nicht gefunden."

[ad_offline]
en = "Ad offline."
de = "Inserat offline."

[ad_deactivated]
en = "Ad deactivated."
de = "Inserat deaktiviert."

[unsupported_association]
en = "This domain is not a supported housing association."
de = "Diese Domain ist keine unterst체tzte Wohnungsbaugesellschaft"

[todo_association]
en = "Support for this housing association is not implemented yet."
de = "Diese Wohnungsbaugesellschaft wurde noch nicht implementiert."

[senior_flat]
en = "This flat is only for elderly people."
de = "Dies ist eine Seniorenwohnung."

[special_need_wbs_flat]
en = "This flat is only for people with a special needs WBS."
de = "Diese Wohnung ist nur f체r Menschen mit einem besonderen Wohnbedarf."

[missing_fields]
en = "Required fields have not been filled."
de = "Pflichtfelder wurden nicht ausgef체llt."

[not_found]
en = "Page was not found."
de = "Diese Seite wurde nicht gefunden."